version: '3.4'

services:
  clean.architecture.inventory.api:
    image: ${DOCKER_REGISTRY-}cleanarchitectureinventoryapi
    build:
      context: .
      dockerfile: Clean.Architecture.Inventory.API/Dockerfile
    ports:
      - "5053:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=server=db;port=3306;database=InventoryControlDB;user=root;password=root;
    depends_on:
      - db
    networks:
      - backend

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: InventoryControlDB
    ports:
      - "3306:3306"
    networks:
      - backend

networks:
  backend:
    driver: bridge
